#include <bits/stdc++.h>
using namespace std;
#include <atcoder/all>
using namespace atcoder;

const long long MOD = 1000000007;
using mint = modint1000000007;

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
    long long N;
    scanf("%lld", &N);
    long long P;
    scanf("%lld", &P);

    return 0;
}
